/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type IngredientUnit = "GRAM" | "MILLILITER" | "PIECE";

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CompositeFood {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  serving_size: Numeric;
  unit: IngredientUnit;
  updated_at: Generated<Timestamp>;
}

export interface CompositeFoodIngredient {
  amount: Numeric;
  composite_food_id: string;
  id: Generated<string>;
  ingredient_id: string;
}

export interface Ingredient {
  calories: Numeric;
  carbs: Numeric;
  created_at: Generated<Timestamp>;
  fats: Numeric;
  id: Generated<string>;
  name: string;
  protein: Numeric;
  serving_size: Numeric;
  unit: IngredientUnit;
  updated_at: Generated<Timestamp>;
}

export interface Meal {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  meal_group_id: string;
  name: string;
  sort_order: number;
  updated_at: Generated<Timestamp>;
}

export interface MealFood {
  amount: Numeric;
  composite_food_id: string | null;
  id: Generated<string>;
  ingredient_id: string | null;
  meal_id: string;
}

export interface MealGroup {
  created_at: Generated<Timestamp>;
  display_as_default: Generated<boolean>;
  id: Generated<string>;
  name: string;
  tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  composite_food: CompositeFood;
  composite_food_ingredient: CompositeFoodIngredient;
  ingredient: Ingredient;
  meal: Meal;
  meal_food: MealFood;
  meal_group: MealGroup;
}
